openapi: 3.0.0
info:
  title: Echo API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /echo:
    post:
      summary: Echo back the received message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
              required:
                - message
      responses:
        '200':
          description: Echo response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message