openapi: 3.0.0
info:
  title: Echo API
  version: 1.0.0
  description: シンプルなエコーAPI

paths:
  /echo:
    post:
      summary: メッセージをエコーする
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './models.yaml#/components/schemas/EchoRequest'
      responses:
        '200':
          description: 成功したエコーレスポンス
          content:
            application/json:
              schema:
                $ref: './models.yaml#/components/schemas/EchoResponse'
